### ISSUE TITLE
add some preview?

### ISSUE THREAD

**Issue by fukemy** [maxime-kouemo/Android-calendar-YearView#1]

**Comment by maxime-kouemo** [comment]
You are right and I apologize. Right now I am working on something else, I have less time to finish it. This weekend I will add some pictures. Please feel free to fork, build and try it. It is not yet unit tested.

**Comment by maxime-kouemo** [comment]
@fukemy You can view a preview [here](https://github.com/maxime-kouemo/Android-calendar-YearView/blob/master/demo_files/demo_year_view.gif) . I don't understand why it is not displayed on the main readme, I think github has a little bug.

The colors aren't fancy as I generate them randomly at runtime to showcase what the YearView can handle. Please visit the project and see how it is applied with many fragments (each representing a year). You can copy the YearView and play with it. If you have any question or comment I'm open to hear. Thank you.

**Comment by fukemy** [comment]
awesome . thanks you
