### ISSUE TITLE
Day click

### ISSUE THREAD

**Issue by jigar1211** [maxime-kouemo/Android-calendar-YearView#3]
Hi

There is an option to click on a particular date and get the exact date. This is very helpful if you give solution

Thanks

**Comment by maxime-kouemo** [comment]
Do you mean a day in a month?

**Comment by jigar1211** [comment]
> Do you mean a day in a month?

Yes Like, I click on 20-12-2020 then It will give me a DateTime of that particular date(Date time of 20-12-2020) but right now it gives me the first day of the month. So any solution for that. It will very helpful for me

Thanks

**Comment by maxime-kouemo** [comment]
Hi, @jigar1211 
I have added the feature your requested. Here is what I added: 
- implemented the selection of a day
- a selection day, can be sticky or not: 
  * When sticky, a selected day by click, will be colored and its timestamp will be available. Clicking on the same date in this mode will just deselect the date. Clicking on another date while one date is selected will deselect the current and select the new one. Only one date can be selected at the time. There is no support for multiple selection so far.
  * When not in sticky mode, a click to select a date will just trigger the date's value once that can be accessible if the click listener is implemented.
- added the possibility to customize the selected day (text color, font type (bold, bold italic, italic, normal), typeface, text size, background color)
- fixed circle and square around a date at selection or when the date represents today

If you have any question, please proceed.
